export const appImages = {
  //   // icons ---->>>
  errorSign: require('../assets/icons/errorSign.png'),
  doneCheck: require('../assets/icons/checkGreen.png'),
  animation: require('../assets/icons/animation.png'),
  appLogo: require('../assets/icons/applogo.png'),
  back: require('../assets/icons/back.png'),
  burgerBar: require('../assets/icons/burgerbar.png'),
  cal: require('../assets/icons/cal.png'),
  chat: require('../assets/icons/chat.png'),
  darkCal: require('../assets/icons/darkcal.png'),
  darkChat: require('../assets/icons/darkchat.png'),
  darkHome: require('../assets/icons/darkhome.png'),
  darkFile: require('../assets/icons/darkfile.png'),
  doctor: require('../assets/icons/doctor.png'),
  email: require('../assets/icons/email.png'),
  file: require('../assets/icons/file.png'),
  home: require('../assets/icons/home.png'),
  location: require('../assets/icons/location.png'),
  lock: require('../assets/icons/lock.png'),
  medicines: require('../assets/icons/medicines.png'),
  mic: require('../assets/icons/mic.png'),
  options: require('../assets/icons/options.png'),
  start: require('../assets/icons/start.png'),
  table: require('../assets/icons/table.png'),
  think: require('../assets/icons/think.png'),
  upload: require('../assets/icons/upload.png'),
  dummy: require('../assets/icons/dummy.png'),
};
